name: prismatic
channels:
  - conda-forge
  - r
dependencies:
  - python=3.10
  - pdal
  - python-pdal
  - gdal
  - whitebox
  - folium
  - mapclassify
  - matplotlib
  - r-base
  - r-devtools
  - r-sf
  - r-ggplot2
  - r-dplyr
  - r-caret
  - r-ggbiplot
  - r-cowplot
  - r-rfUtilities
  - r-gridextra
  - r-lidR
  - r-randomForest
  - r-assertthat
  - r-stringr
  - r-bvls #bvls()
  - r-tidyr #pivot_longer()
  - r-terra
  - r-neonUtilities
  - r-neonOS
  - r-geoNEON
  - r-glue
  - pip
  - pip:
    - gdown
    - pygbif
    - geopandas
    - rpy2>=3.5.11
    - tqdm
    - laspy[lazrs, laszip]
    - open3d
    - sklearn
    - hydra-core
    - hydra_colorlog
