name: prisma
channels:
  - conda-forge
  - r
dependencies:
  - python=3.9
  - pdal
  - python-pdal
  - gdal
  - pygbif
  - folium
  - mapclassify
  - matplotlib
  - r-base
  - r-neonUtilities
  - r-neonOS
  - r-sp
  - r-raster
  - r-devtools
