name: prisma
channels:
  - conda-forge
  - r
dependencies:
  - python=3.10
  - pdal
  - python-pdal
  - gdal
  - folium
  - mapclassify
  - matplotlib
  - pip
  - pip:
    - pygbif
    - geopandas
  # - pygbif
  # - r-base
  # - r-neonUtilities
  # - r-neonOS
  # - r-sp
  # - r-raster
  # - r-devtools
