name: prismatic
channels:
  - conda-forge
  - r
dependencies:
  - python=3.10
  - pdal
  - python-pdal
  - gdal
  - whitebox
  - folium
  - mapclassify
  - matplotlib
  - r-base
  - r-sp
  - r-sf
  - r-raster
  - r-devtools
  - r-lidr
  - rpy2
  - pip
  - pip:
    - gdown
    - pygbif
    - geopandas
    - rpy2>=3.5.11
    - tqdm
    - laspy[lazrs, laszip]
    - open3d
    - sklearn
    - hydra-core
    - hydra_colorlog
