name: prisma-test
channels:
  - conda-forge
  - r
dependencies:
  - python=3.10
  - pdal
  - python-pdal
  - gdal
  - whitebox
  - folium
  - mapclassify
  - matplotlib
  - r-base
  - r-sp
  - r-raster
  - r-devtools
  - pip
  - pip:
    - pygbif
    - geopandas
    - rpy2
    - tqdm
    - hydra-core
    - hydra_colorlog
